// Product definitions for all fertilizer sections

export const seedTreatmentProducts = [
  { value: 'root-shoot', label: 'Root & Shoot', defaultRate: '3-4', defaultUnit: 'L/tonne of seed', contains: ['N', 'P', 'K', 'Trace Elements'], nutrientPercents: ['N 10%', 'P 5%', 'K 8%', 'Trace Elements 2%'] },
  { value: 'nutri-bam', label: 'Nutri-Life BAM', defaultRate: '5', defaultUnit: 'L/tonne of seed', contains: ['Beneficial Microbes'], nutrientPercents: ['Beneficial Microbes'] },
  { value: 'nutri-platform', label: 'Nutri-Life Platform', defaultRate: '1.3', defaultUnit: 'kg/tonne of seed', contains: ['Beneficial Microbes'], nutrientPercents: ['Beneficial Microbes'] },
  { value: 'mycorrhizal', label: 'Mycorrhizal Inoculant', defaultRate: '10', defaultUnit: 'g/ha', contains: ['Mycorrhizae'], nutrientPercents: ['Mycorrhizae'] },
  { value: 'rhizobium', label: 'Rhizobium Bacteria', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Rhizobium'], nutrientPercents: ['Rhizobium'] },
  { value: 'biochar', label: 'Biochar Coating', defaultRate: '2', defaultUnit: 'kg/ha', contains: ['Biochar'], nutrientPercents: ['Biochar'] },
  { value: 'trichoderma', label: 'Trichoderma Fungi', defaultRate: '8', defaultUnit: 'g/ha', contains: ['Trichoderma'], nutrientPercents: ['Trichoderma'] },
  { value: 'bacillus-subtilis', label: 'Bacillus subtilis', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Bacillus subtilis'], nutrientPercents: ['Bacillus subtilis'] },
  { value: 'pseudomonas-fluorescens', label: 'Pseudomonas fluorescens', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Pseudomonas fluorescens'], nutrientPercents: ['Pseudomonas fluorescens'] },
  { value: 'azospirillum', label: 'Azospirillum', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Azospirillum'], nutrientPercents: ['Azospirillum'] },
  { value: 'azotobacter', label: 'Azotobacter', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Azotobacter'], nutrientPercents: ['Azotobacter'] },
  { value: 'phosphobacteria', label: 'Phosphobacteria', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Phosphobacteria'], nutrientPercents: ['Phosphobacteria'] },
  { value: 'actinomycetes', label: 'Actinomycetes', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Actinomycetes'], nutrientPercents: ['Actinomycetes'] },
  { value: 'streptomyces', label: 'Streptomyces', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Streptomyces'], nutrientPercents: ['Streptomyces'] },
  { value: 'frankia', label: 'Frankia', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Frankia'], nutrientPercents: ['Frankia'] },
  { value: 'penicillium', label: 'Penicillium', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Penicillium'], nutrientPercents: ['Penicillium'] },
  { value: 'aspergillus', label: 'Aspergillus', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Aspergillus'], nutrientPercents: ['Aspergillus'] },
  { value: 'phosphate-solubilizing-bacteria', label: 'Phosphate Solubilizing Bacteria', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Phosphate Solubilizing Bacteria'], nutrientPercents: ['Phosphate Solubilizing Bacteria'] },
  { value: 'potassium-solubilizing-bacteria', label: 'Potassium Solubilizing Bacteria', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Potassium Solubilizing Bacteria'], nutrientPercents: ['Potassium Solubilizing Bacteria'] },
  { value: 'silicate-solubilizing-bacteria', label: 'Silicate Solubilizing Bacteria', defaultRate: '5', defaultUnit: 'g/ha', contains: ['Silicate Solubilizing Bacteria'], nutrientPercents: ['Silicate Solubilizing Bacteria'] }
];

export const productList = [
  { label: 'K-Rich™', nutrientContent: { Potassium: 33.29 }, description: 'A pH-buffered liquid potassium citrate designed for foliar application during fruit/seed fill. Its citrate form enhances potassium uptake and rapidly corrects deficiencies.' },
  { label: 'Cal-Tech™', nutrientContent: { Nitrogen: 11.71, Boron: 0.43, Calcium: 13.36 }, description: 'An amino-chelated liquid calcium product with added boron, nitrogen, trace elements, and vitamin B12. Enhances cell wall strength, fruit quality, and disease resistance.' },
  { label: 'Calcium Fulvate™', nutrientContent: { Nitrogen: 6.78, Sulphur: 0.54, Boron: 0.0207, Calcium: 8.93, Copper: 0.0785, Zinc: 0.0807, Iron: 0.17, Potassium: 1.32, Manganese: 0.21, Molybdenum: 0.0102 }, description: 'Chelated calcium with fulvic acid, enriched with a broad spectrum of trace minerals to improve nutrient uptake.' },
  { label: 'Citrus-Tech Triple Ten™', nutrientContent: { Nitrogen: 10.48, Sulphur: 0.22, Boron: 0.0347, Calcium: 0.0558, Copper: 0.0197, Phosphorus: 10.23, Zinc: 0.0743, Iron: 0.1459, Potassium: 10.69, Manganese: 0.0607, Molybdenum: 0.0039, Selenium: 0.0198 }, description: 'A full-spectrum NPK foliar formula (10-10-10) enriched with chelated trace elements, seaweed extract, fulvic acid, and vitamins.' },
  { label: 'Cloak Spray Oil™', nutrientContent: {}, description: 'A premium spreader/sticker blend of cold-pressed canola oil and omega-3 fish oil, which enhances foliar nutrient absorption and spray efficiency.' },
  { label: 'Nutri-Carb-N™', nutrientContent: { Ammonium: 15.18, Potassium: 1.1 }, description: 'A humic-acid-stabilised nitrogen solution that improves nitrogen use efficiency, reduces leaching and volatilisation, and promotes sustained crop growth and productivity.' },
  { label: 'Phos-Force™', nutrientContent: { Nitrogen: 4.2, Calcium: 4.3, Phosphorus: 14.3, Iron: 3.5 }, description: 'An advanced phosphate fertiliser delivering phosphate, calcium, and iron in a plant-available liquid.' },
  { label: 'Photo-Finish™', nutrientContent: { Potassium: 10.6, Silicon: 10.38 }, description: 'A silica-rich foliar containing potassium, humates, and kelp to improve cell wall strength, pest resilience, photosynthesis, and overall plant health during the finishing phase.' },
  { label: 'Potassium Silicate™', nutrientContent: { Potassium: 15.3, Silicon: 17.3 }, description: 'A soluble source of potassium and silicon designed to enhance plant structure, disease resistance, and tolerance to environmental stress.' },
  { label: 'Seed-Start™', nutrientContent: {}, description: 'A specialised liquid for seedling establishment, containing growth promoters, minerals, enzymes, and natural biostimulants to support early root development and plant vigor.' },
  { label: 'Trio (CMB)™', nutrientContent: { Nitrogen: 13.73, Boron: 0.26, Magnesium: 2.38, Calcium: 15.3, Zinc: 0.006, Iron: 0.1 }, description: 'A balanced liquid formula containing calcium, magnesium, and boron, plus trace minerals and kelp. Supports plant strength, flowering, fruit set, and disease resilience.' },
  { label: 'Triple Ten™', nutrientContent: { Nitrogen: 10.48, Sulphur: 0.22, Boron: 0.0347, Calcium: 0.0558, Copper: 0.0197, Phosphorus: 10.23, Zinc: 0.0743, Iron: 0.1459, Potassium: 10.69, Manganese: 0.0607, Molybdenum: 0.0039, Selenium: 0.0198 }, description: 'A state‑of‑the‑art 10‑10‑10 liquid fertiliser combining hot‑mix NPK with chelated trace elements, fulvic acid, seaweed, vitamins, amino acids, saponins and triacontanol.' },
  { label: 'Tsunami™ Super Spreader', nutrientContent: {}, description: 'A patented silicon‑based non‑ionic wetter/spreader that dramatically improves spray coverage and uptake, especially on hard‑to‑wet leaf surfaces.' },
  { label: 'Activated Char Condensate (ACC)™', nutrientContent: {}, description: 'A breakthrough wood‑vinegar (smoke condensate from biochar) using LipoZoom liposomal technology.' },
  { label: 'Aloe-Tech™', nutrientContent: {}, description: 'A natural aloe‑based plant and microbial promotant, designed to enhance soil biology, stress resilience and plant vigour.' },
  { label: 'Amino-Max™', nutrientContent: { Ammonium: 5.78, Nitrate: 5.78, 'Amino Acids': 40 }, description: 'A high‑amino acid concentrate. Ideal for supporting plant metabolism, stress recovery and microbial stimulation.' },
  { label: 'Brix-Fix™', nutrientContent: {}, description: 'A liquid concentrate of seven plant growth promotants designed to increase Brix (sugar) levels in crops.' },
  { label: 'Nutri-Kelp™', nutrientContent: {}, description: 'A premium seaweed‑derived plant growth promoter, rich in natural biostimulants.' },
  { label: 'Nutri-Sea Liquid Fish™', nutrientContent: {}, description: 'A liquid fish‑based fertiliser and microbial stimulant, included in the Natural Soil‑Life & Plant Growth Promoters.' },
  { label: 'Nutri-Stim Saponins™', nutrientContent: {}, description: 'A saponin‑rich biostimulant formulation designed to stimulate soil microbes and enhance plant root activity.' },
  { label: 'Nutri-Stim Triacontanol™', nutrientContent: {}, description: 'A natural plant growth promoter based on triacontanol, included in the soil‑life promoter range to enhance growth and yield.' },
  { label: 'Nutri-Tech Black Gold®', nutrientContent: {}, description: 'A liquid soil‑life and plant growth promoter designed to build Brix, improve stress and frost resistance.' },
  { label: 'Root & Shoot™', nutrientContent: {}, description: 'A biological seed treatment containing beneficial microbes and biostimulants to enhance root development, early vigor, and plant resilience.' },
  { label: 'SeaChange KFF™', nutrientContent: {}, description: 'A kelp-based liquid fertiliser (SeaChange range) enriched with kelp biostimulants to boost plant health, stress resilience, and crop performance.' },
  { label: 'SeaChange Liquid Kelp™', nutrientContent: {}, description: 'Premium liquid seaweed extract providing natural growth regulators and micronutrients to enhance soil biology, drought resistance, and overall plant vigor.' },
  { label: 'Tri-Kelp™', nutrientContent: {}, description: 'A soluble kelp powder seed treatment featuring three types of kelp to improve germination, root and shoot growth, and stimulate beneficial soil microbes.' },
  { label: 'Nutri-Key Boron Shuttle™', nutrientContent: { Nitrogen: 0.29, Sulphur: 0.53, Boron: 3.61, Magnesium: 0.0938, Copper: 0.049, Zinc: 0.19, Iron: 0.31, Potassium: 0.51, Manganese: 0.15, Molybdenum: 0.0098, Carbon: 3.38 }, description: 'A foliar chelated boron formulation containing 3.6% B, supported by a full background of synergistic nutrition.' },
  { label: 'Nutri-Key Calcium Shuttle™', nutrientContent: { Nitrogen: 7.25, Sulphur: 0.26, Boron: 0.0433, Magnesium: 0.0363, Calcium: 9.81, Copper: 0.0245, Zinc: 0.093, Iron: 0.15, Potassium: 0.23, Manganese: 0.0757, Molybdenum: 0.0049, Silicon: 0.0217, Carbon: 5.27 }, description: 'A chelated calcium foliar using Shuttle® technology.' },
  { label: 'Nutri-Key Cobalt Shuttle™', nutrientContent: { Cobalt: 3.1, Zinc: 2.8 }, description: 'A foliar chelated cobalt formulation with 3.1 % Co and 2.8 % Zn, designed to address cobalt deficiencies important for nitrogen-fixing legumes and seed formation.' },
  { label: 'Nutri-Key Copper Shuttle™', nutrientContent: { Nitrogen: 0.52, Sulphur: 4.29, Boron: 0.0866, Magnesium: 0.0675, Copper: 7.64, Zinc: 0.19, Iron: 0.31, Potassium: 0.27, Manganese: 0.15, Molybdenum: 0.0098, Carbon: 4.62 }, description: 'A foliar copper formulation with 7.6 % Cu and support nutrients. Chelated to reduce antagonism, improve uptake, and strengthen cell walls and seed health.' },
  { label: 'Nutri-Key Hydro-Shuttle™', nutrientContent: { Nitrogen: 2.14, Carbon: 21.15 }, description: 'A carbohydrate-rich chelator (Hydro-Shuttle®) delivering ~21% C with moderate N—used to support foliar nutrient uptake and microbial life on leaf surfaces.' },
  { label: 'Nutri-Key Iron Shuttle™', nutrientContent: { Nitrogen: 0.52, Sulphur: 4.41, Boron: 0.0866, Magnesium: 0.0678, Copper: 0.049, Zinc: 0.19, Iron: 7.21, Potassium: 0.34, Manganese: 0.15, Molybdenum: 0.0098, Carbon: 4.38 }, description: 'A chelated iron foliar (~7.2% Fe) supported by background nutrients to boost chlorophyll production and rapidly correct iron deficiency.' },
  { label: 'Nutri-Key Magnesium Shuttle™', nutrientContent: { Nitrogen: 0.45, Sulphur: 6.24, Boron: 0.0866, Magnesium: 4.44, Copper: 0.049, Zinc: 0.19, Iron: 0.31, Potassium: 0.31, Manganese: 0.15, Molybdenum: 0.0098, Carbon: 3.9 }, description: 'A foliar Mg application (~4.4 % Mg) with supporting macro and micro nutrients.' },
  { label: 'Nutri-Key Manganese Shuttle™', nutrientContent: { Nitrogen: 0.53, Sulphur: 8.15, Boron: 0.0866, Magnesium: 0.0675, Copper: 0.049, Zinc: 0.19, Iron: 0.31, Potassium: 0.27, Manganese: 13.19, Molybdenum: 0.0098, Carbon: 4.7 }, description: 'A high-analysis foliar Mn formulation (~13.2% Mn) featuring advanced chelation for improved uptake.' },
  { label: 'Nutri-Key Moly Shuttle™', nutrientContent: { Nitrogen: 0.18, Molybdenum: 4.76, Carbon: 1.6 }, description: 'A foliar Mo product (~4.8 % Mo) using Shuttle® chelation. Enhances enzyme systems and nitrogen metabolism, especially for legumes.' },
  { label: 'Nutri-Key Shuttle Seven™', nutrientContent: { Nitrogen: 0.43, Sulphur: 4.72, Boron: 0.87, Magnesium: 0.67, Cobalt: 0.000034, Copper: 0.49, Zinc: 1.86, Iron: 3.06, Potassium: 2.63, Manganese: 1.51, Molybdenum: 0.000975, Selenium: 0.43, Carbon: 3.04 }, description: 'Seven-nutrient foliar complex combining B, Cu, Fe, Mn, Mo, Se, Zn using Shuttle® chelation.' },
  { label: 'Nutri-Key Zinc Shuttle™', nutrientContent: { Nitrogen: 0.73, Sulphur: 4.35, Boron: 0.0866, Magnesium: 0.0675, Copper: 0.049, Zinc: 8.17, Iron: 0.31, Potassium: 0.27, Manganese: 0.15, Molybdenum: 0.0098, Carbon: 6.54 }, description: 'A foliar Zn product (~8.2 % Zn) with supporting nutrition for optimal uptake and correction of zinc deficiencies.' },
  { label: 'Boron Essentials™', nutrientContent: { Nitrogen: 0.05, Boron: 3.09, Zinc: 0.04 }, description: 'A foliar boron spray (~3 % B) with minimal N and Zn. Designed for precise B correction during flowering and fruit-set.' },
  { label: 'Copper Essentials™', nutrientContent: { Nitrogen: 0.12, Sulphur: 2.55, Magnesium: 0.0352, Calcium: 0.0247, Copper: 4.9, Potassium: 0.14 }, description: 'A foliar copper spray (~4.9 % Cu) with support nutrients. Targets copper deficiencies affecting disease resistance and quality.' },
  { label: 'Iron Essentials™', nutrientContent: { Nitrogen: 0.12, Sulphur: 3.49, Magnesium: 0.0351, Calcium: 0.0247, Iron: 6, Potassium: 0.14 }, description: 'A pure iron foliar (~6 % Fe) with minimal support nutrients to quickly correct chlorosis and boost photosynthesis.' },
  { label: 'Manganese Essentials™', nutrientContent: { Nitrogen: 0.12, Sulphur: 6.52, Magnesium: 0.0352, Calcium: 0.0247, Manganese: 0.13, Silicon: 10.96 }, description: 'A foliar manganese spray (~0.13 % Mn) with silicon booster. Ideal for seed/grain crops prone to Mn deficiency.' },
  { label: 'Multi-Boost™', nutrientContent: { Nitrogen: 2.29, Sulphur: 6.2, Boron: 0.033, Magnesium: 0.64, Calcium: 5.96, Copper: 0.0245, Phosphorus: 0.29, Zinc: 0.0536, Iron: 0.0708, Potassium: 0.66, Manganese: 0.0483, Molybdenum: 0.013 }, description: 'A multi-nutrient foliar blend with balanced macro and micro elements to deliver broad corrective nutrition.' },
  { label: 'Multi-Min™', nutrientContent: { Nitrogen: 4.24, Sulphur: 4.12, Boron: 0.2, Magnesium: 1.49, Calcium: 0.0186, Copper: 0.78, Phosphorus: 0.17, Zinc: 0.81, Iron: 1.44, Potassium: 2.45, Manganese: 2.05, Molybdenum: 0.1 }, description: 'A comprehensive foliar multi-mineral spray for crop conditions requiring mid-level correction across many nutrients.' },
  { label: 'Multi-Plex™', nutrientContent: { Nitrogen: 10.22, Sulphur: 0.23, Boron: 0.0347, Copper: 0.0198, Phosphorus: 10.09, Zinc: 0.0743, Iron: 0.14, Potassium: 10.04, Manganese: 0.0607, Molybdenum: 0.0039 }, description: 'A powerful corrective spray (10‑10 NPK plus micro-trace) for comprehensive foliar nutrition in high-yield crops.' },
  { label: 'Zinc Essentials™', nutrientContent: { Nitrogen: 0.12, Sulphur: 3.95, Magnesium: 0.0351, Calcium: 0.0247, Zinc: 7.95, Iron: 0.14 }, description: 'A herbaceous foliar zinc spray (~8 % Zn) with supporting nutrients, tailored to correct zinc deficiencies.' },
  { label: 'CalMag-Life Organic™', nutrientContent: { Magnesium: 9.68, Calcium: 20.26 }, description: 'An organic Ca–Mg blend derived from natural minerals to improve soil structure and correct acidic soil deficiencies.' },
  { label: 'Dia-Life Organic™', nutrientContent: { Boron: 0.68, Magnesium: 0.0277, Calcium: 0.16, Iron: 0.32, Silicon: 12.51 }, description: 'A diatomaceous earth-based mineral blend providing bioavailable silica plus trace nutrients to boost plant and soil resilience.' },
  { label: 'Gyp-Life Organic™', nutrientContent: { Sulphur: 15.31, Calcium: 19.55 }, description: 'A soluble gypsum product delivering sulfur and calcium to improve soil structure, correct subsoil acidity and enhance root development.' },
  { label: 'Lime-Life Organic™', nutrientContent: { Magnesium: 1.05, Calcium: 39.37 }, description: 'A finely ground organic lime that corrects soil pH while supplying calcium and magnesium for improved fertility.' },
  { label: 'Mag-Life Organic™', nutrientContent: { Magnesium: 21.33 }, description: 'A high-magnesium organic mineral to correct soil Mg deficiencies and support chlorophyll formation.' },
  { label: 'Phos-Life Organic™', nutrientContent: { Magnesium: 0.34, Calcium: 24.56, Copper: 0.0162, Phosphorus: 10.71, Zinc: 0.14, Iron: 0.86, Potassium: 0.15, Manganese: 1.66, Silicon: 10.73 }, description: 'A mineral phosphate product rich in phosphorus, calcium and silica—designed to boost root growth and soil fertility.' },
  { label: 'Sili-Cal (B)™', nutrientContent: { Sulphur: 0.13, Boron: 0.51, Magnesium: 0.64, Calcium: 21.59, Iron: 0.0861, Potassium: 0.23, Silicon: 3.34 }, description: 'A calcium–silicate–boron blend supplying cell wall strength, stress resistance and support for crop quality.' },
  { label: 'Worm Juice', nutrientContent: {}, description: 'A concentrated, biologically active worm-cast extract designed to prime and enhance soil vitality.' },
  { label: 'Compost Tea Extract', nutrientContent: {}, description: 'A living liquid extract derived from high-quality compost, rich in beneficial bacteria, fungi, and bio-stimulatory metabolites.' },
  { label: 'Urea', nutrientContent: { Ammonium: 46 }, description: 'A highly concentrated nitrogen fertilizer that promotes vigorous vegetative growth and rapid green-up in crops.' },
  { label: 'Calcium Nitrate', nutrientContent: { Calcium: 17, Nitrate: 12 }, phLogic: { min_pH: null, max_pH: 7.5 }, releaseType: 'fast' },
  { label: 'Potassium Nitrate', nutrientContent: { Potassium: 39, Nitrate: 14 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Sodium Nitrate (Chile Nitrate)', nutrientContent: { Sodium: 26, Nitrate: 16 }, phLogic: { min_pH: null, max_pH: 8.0 }, releaseType: 'fast' },
  { label: 'Zinc Nitrate', nutrientContent: { Zinc: 12, Nitrate: 8 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Iron Nitrate', nutrientContent: { Iron: 6, Nitrate: 10 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Copper Nitrate', nutrientContent: { Copper: 8, Nitrate: 12 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Ammonium Nitrate', nutrientContent: { Ammonium: 17, Nitrate: 17 }, phLogic: { min_pH: 5.5, max_pH: 7.5 }, releaseType: 'fast' },
  { label: 'UAN Solution (Urea Ammonium Nitrate)', nutrientContent: { Urea: 18, Ammonium: 9, Nitrate: 9 }, phLogic: { min_pH: 5.5, max_pH: 7.5 }, releaseType: 'fast' },
  { label: 'Calcium Ammonium Nitrate (CAN)', nutrientContent: { Calcium: 8, Magnesium: 2, Ammonium: 13, Nitrate: 13 }, phLogic: { min_pH: 5.5, max_pH: 7.5 }, releaseType: 'fast' },
  { label: 'Ammonium Polyphosphate (APP)', nutrientContent: { Phosphorus: 10, Ammonium: 11 }, phLogic: { min_pH: 5.5, max_pH: 8.0 }, releaseType: 'fast' },
  { label: 'Ammonium Chloride', nutrientContent: { Ammonium: 25 }, phLogic: { min_pH: 5.0, max_pH: 7.0 }, releaseType: 'fast' },
  { label: 'Ammonium Acetate', nutrientContent: { Ammonium: 12 }, phLogic: { min_pH: 5.0, max_pH: 8.5 }, releaseType: 'fast' },
  { label: 'Triple Superphosphate (TSP)', nutrientContent: { Phosphorus: 45, Calcium: 19 }, phLogic: { min_pH: 5.5, max_pH: 7.5 }, releaseType: 'fast' },
  { label: 'Monoammonium Phosphate (MAP)', nutrientContent: { Phosphorus: 21.9, Ammonium: 10 }, phLogic: { min_pH: 6.5, max_pH: 8.5 }, releaseType: 'fast' },
  { label: 'Diammonium Phosphate (DAP)', nutrientContent: { Phosphorus: 20, Ammonium: 18 }, phLogic: { min_pH: 5.0, max_pH: 6.8 }, releaseType: 'fast' },
  { label: 'Rock Phosphate', nutrientContent: { Phosphorus: 25, Calcium: 30 }, phLogic: { min_pH: null, max_pH: 6.0 }, releaseType: 'very slow' },
  { label: 'Agricultural Limestone (CaCO₃)', nutrientContent: { Calcium: 40 }, phLogic: { min_pH: null, max_pH: 6.5 }, releaseType: 'slow' },
  { label: 'Bone Meal', nutrientContent: { Calcium: 26, Phosphorus: 14 }, phLogic: { min_pH: null, max_pH: 7.0 }, releaseType: 'slow' },
  { label: 'Fish Bone Meal', nutrientContent: { Calcium: 20, Phosphorus: 10, Ammonium: 5 }, phLogic: { min_pH: 5.0, max_pH: 7.5 }, releaseType: 'slow' },
  { label: 'Calcium Chloride', nutrientContent: { Calcium: 27 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Muriate of Potash (Potassium Chloride)', nutrientContent: { Potassium: 60 }, phLogic: { min_pH: 5.5, max_pH: 8.5 }, releaseType: 'fast' },
  { label: 'Langbeinite', nutrientContent: { Potassium: 22, Magnesium: 11, Sulphur: 22 }, phLogic: { min_pH: 5.5, max_pH: 8.0 }, releaseType: 'moderate' },
  { label: 'Potassium Magnesium Sulfate', nutrientContent: { Potassium: 22, Magnesium: 11, Sulphur: 22 }, phLogic: { min_pH: 5.5, max_pH: 8.0 }, releaseType: 'moderate' },
  { label: 'Potassium Thiosulfate', nutrientContent: { Potassium: 25, Sulphur: 17 }, phLogic: { min_pH: 5.0, max_pH: 8.0 }, releaseType: 'fast' },
  { label: 'Potassium Carbonate', nutrientContent: { Potassium: 55 }, phLogic: { min_pH: 5.5, max_pH: 7.5 }, releaseType: 'fast' },
  { label: 'Potassium Acetate', nutrientContent: { Potassium: 25 }, phLogic: { min_pH: 5.5, max_pH: 8.0 }, releaseType: 'fast' },
  { label: 'Wood Ash', nutrientContent: { Potassium: 5, Calcium: 10, Magnesium: 2, Phosphorus: 1 }, phLogic: { min_pH: 5.0, max_pH: 7.0 }, releaseType: 'slow' },
  { label: 'Dolomitic Lime', nutrientContent: { Calcium: 20, Magnesium: 10 }, phLogic: { min_pH: null, max_pH: 6.5 }, releaseType: 'slow' },
  { label: 'Kieserite (Magnesium Sulfate Monohydrate)', nutrientContent: { Magnesium: 16, Sulphur: 22 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'moderate' },
  { label: 'Epsom Salt (Magnesium Sulfate Heptahydrate)', nutrientContent: { Magnesium: 9.9, Sulphur: 13 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Thermophosphate', nutrientContent: { Calcium: 20, Magnesium: 2, Phosphorus: 18 }, phLogic: { min_pH: 5.5, max_pH: 7.5 }, releaseType: 'slow' },
  { label: 'Magnesium Nitrate', nutrientContent: { Magnesium: 10.5, Nitrate: 11 }, phLogic: { min_pH: 5.5, max_pH: 8.0 }, releaseType: 'fast' },
  { label: 'Magnesium Chloride', nutrientContent: { Magnesium: 12 }, phLogic: { min_pH: 5.0, max_pH: 8.0 }, releaseType: 'fast' },
  { label: 'Sulfur-Rich Compost', nutrientContent: { Sulphur: 2, Calcium: 3, Magnesium: 2, Potassium: 2, Phosphorus: 1, Ammonium: 2 }, phLogic: { min_pH: 5.0, max_pH: 8.0 }, releaseType: 'slow' },
  { label: 'Elemental Sulfur', nutrientContent: { Sulphur: 90 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'very slow' },
  { label: 'Ammonium Sulfate', nutrientContent: { Ammonium: 21, Sulphur: 24 }, phLogic: { min_pH: 5.0, max_pH: 8.5 }, releaseType: 'fast' },
  { label: 'Potassium Sulfate (Sulfate of Potash)', nutrientContent: { Potassium: 42.5, Sulphur: 18.4 }, phLogic: { min_pH: 5.0, max_pH: 8.5 }, releaseType: 'fast' },
  { label: 'Ammonium Thiosulfate', nutrientContent: { Sulphur: 26, Ammonium: 12 }, phLogic: { min_pH: 5.0, max_pH: 8.5 }, releaseType: 'moderate' },
  { label: 'Sulfur-Coated Urea', nutrientContent: { Sulphur: 15, Ammonium: 35 }, phLogic: { min_pH: 5.0, max_pH: 8.0 }, releaseType: 'slow' },
  { label: 'Chicken Manure', nutrientContent: { Phosphorus: 2.5, Ammonium: 3, Potassium: 2, Calcium: 3, Magnesium: 1, Sulphur: 0.5 }, phLogic: { min_pH: 5.0, max_pH: 8.0 }, releaseType: 'slow' },
  { label: 'NTS Fast Fulvic™', nutrientContent: { Nitrate: 0.1, Ammonium: 0.1, Calcium: 0.1, Magnesium: 0.1, Potassium: 0.1, Phosphorus: 0.1, Sulphur: 0.1 }, phLogic: { min_pH: 4, max_pH: 12 }, releaseType: 'fast',description: 'An 8 % fulvic acid liquid possessing a myriad of yield-enhancing qualities.' },
  { label: 'NTS Fulvic Acid Powder™', nutrientContent: { Nitrate: 0.1, Ammonium: 0.1, Calcium: 0.1, Magnesium: 0.1, Potassium: 0.1, Phosphorus: 0.1, Sulphur: 0.1 }, phLogic: { min_pH: 4, max_pH: 12 }, releaseType: 'fast' ,description: 'Fulvic acid in a concentrated, soluble powder – the most versatile and productive input in agriculture, in freight-friendly form.'},
  { label: 'NTS FulvX™ Powder', nutrientContent: { Nitrate: 0.1, Ammonium: 0.1, Calcium: 0.1, Magnesium: 0.1, Potassium: 0.1, Phosphorus: 0.1, Sulphur: 0.1 }, phLogic: { min_pH: 4, max_pH: 12 }, releaseType: 'fast' ,description: 'Concentrated soluble fulvic & humic acid.'},
  { label: 'NTS Liquid Humus™', nutrientContent: { Nitrate: 0.1, Ammonium: 0.1, Calcium: 0.1, Magnesium: 0.1, Potassium: 0.1, Phosphorus: 0.1, Sulphur: 0.1 }, phLogic: { min_pH: 4, max_pH: 12 }, releaseType: 'fast' ,description: 'A liquid humic acid suspension derived from premium humates, designed to improve soil structure, nutrient retention, and biological activity.'},
  { label: 'NTS Soluble Humate Granules™', nutrientContent: { Nitrate: 0.1, Ammonium: 0.1, Calcium: 0.1, Magnesium: 0.1, Potassium: 0.1, Phosphorus: 0.1, Sulphur: 0.1 }, phLogic: { min_pH: 4, max_pH: 12 }, releaseType: 'fast' ,description: 'High-purity, fully soluble humate granules for use in liquid formulations or direct soil application to enhance CEC, nutrient chelation, and microbial health.' },
  { label: 'NTS Super Soluble Humates™', nutrientContent: { Nitrate: 0.1, Ammonium: 0.1, Calcium: 0.1, Magnesium: 0.1, Potassium: 0.1, Phosphorus: 0.1, Sulphur: 0.1 }, phLogic: { min_pH: 4, max_pH: 12 }, releaseType: 'fast' ,description: 'Highly refined, super-soluble humic acid powder for preparing DIY liquid humus, boosting nutrient efficiency, and stimulating beneficial soil microbes.'},
  { label: 'Life Force® Carbon™', nutrientContent: { Nitrate: 0.1, Ammonium: 0.1, Calcium: 0.1, Magnesium: 0.1, Potassium: 0.1, Phosphorus: 0.1, Sulphur: 0.1 }, phLogic: { min_pH: 4, max_pH: 12 }, releaseType: 'slow' },
  { label: 'Life Force Gold™', nutrientContent: { Calcium: 9.8, Potassium: 2.4, Ammonium: 2, Phosphorus: 1.55, Sulphur: 4 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'moderate' },
  { label: 'NTS Soft Rock™', nutrientContent: { Calcium: 20, Phosphorus: 9 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'slow', url: 'https://nutri-tech.com.au/collections/composted-fertilisers/products/nts-soft-rock' },
  { label: 'Nutri-Gyp™ Natural Gypsum', nutrientContent: { Calcium: 19, Sulphur: 15 }, phLogic: { min_pH: 4.5, max_pH: 8.4 }, releaseType: 'moderate' },
  { label: 'Nutri-Cal™', nutrientContent: { Potassium: 2.5, Magnesium: 3.26, Sulphur: 4.63 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Nutri-Phos Super Active™', nutrientContent: { Calcium: 28.9, Phosphorus: 12.6 }, phLogic: { min_pH: 6.0, max_pH: 7.0 }, releaseType: 'slow' },
  { label: 'Soluble Boron™', nutrientContent: { Boron: 22 }, phLogic: { min_pH: 5.0, max_pH: 8.0 }, releaseType: 'fast' },
  { label: 'Boric Acid™', nutrientContent: { Boron: 17.5 }, phLogic: { min_pH: 5.5, max_pH: 8.5 }, releaseType: 'moderate' },
  { label: 'Biomin Calcium™', nutrientContent: { Calcium: 15, Nitrogen: 3.6 }, phLogic: { min_pH: 4.0, max_pH: 8.0 }, releaseType: 'fast' },  
  { label: 'Nutri-Life B.Sub™', nutrientContent: { Bacillus_subtilis: '2 × 10^8 cfu/mL' }, description: 'A concentrated inoculum of Bacillus subtilis to support plant growth, improve rhizosphere balance and enhance natural defence responses.' },
  { label: 'Nutri-Life Bio-N™', nutrientContent: { Azotobacter_vinelandii: 'free-living nitrogen fixer' }, description: 'Contains Azotobacter vinelandii, a free-living nitrogen fixer that boosts nitrogen availability, root growth and soil moisture efficiency.' }, 
  { label: 'Nutri-Life Bio-Plex™', nutrientContent: { Azotobacter_species: 'present', Bacillus_subtilis: 'present' }, description: 'A foliar inoculum with Azotobacter spp. and Bacillus subtilis to fix nitrogen, release growth promotants and support leaf-surface microbial balance.' },
  { label: 'Nutri-Life Bio-P™', nutrientContent: { Bacillus_polymyxa: 'present', Bacillus_megaterium: 'present' }, description: 'A phosphorus-mobilising blend of Bacillus polymyxa and Bacillus megaterium that improves P availability, root growth and crop quality.' }, 
  { label: 'Nutri-Life Micro-Force™', nutrientContent: { beneficial_microbes: 'proprietary blend of soil & plant bacteria' }, description: 'A microbial blend designed to create a strong bacterial-dominant brew that improves nutrient release, nitrogen fixation and crop resilience.' },
  { label: 'Nutri-Life Root-Guard™', nutrientContent: { Trichoderma_harzianum: 'present' }, description: 'A talc-based Trichoderma inoculant that boosts root health, strengthens the rhizosphere and supports plant resilience.' },
  { label: 'Nutri-Life Platform™', nutrientContent: { Glomus_intraradices: 'present', Glomus_clarum: 'present', Glomus_aggregatum: 'present', Glomus_deserticola: 'present', Glomus_macrocarpum: 'present', Glomus_caledonium: 'present', Glomus_mosseae: 'present', Gigaspora_rosea: 'present', Gigaspora_margarita: 'present', Scutelospora_heterogama: 'present', Azospirillum_brasilense: 'present', Azotobacter_chroococcum: 'present', Gluconacetobacter_diazotrophicus: 'present', Bacillus_megaterium: 'present', Pseudomonas_fluorescens: 'present' }, description: 'A comprehensive AMF and bacterial inoculant that enhances root development, nutrient uptake and soil bio-balance.' },
  { label: 'Nutri-Life Sudo-Shield™', nutrientContent: { Pseudomonas_fluorescens: 'present' }, description: 'A Pseudomonas fluorescens inoculant that supports plant defence, recovery from stress and root-zone microbial balance.' },
  { label: 'Nutri-Life Tricho-Shield™', nutrientContent: { Trichoderma_harzianum: 'present', Trichoderma_lignorum: 'present', Trichoderma_koningii: 'present' }, description: 'A blend of Trichoderma species that strengthens root health, improves bio-balance and supports crop resilience.' },
  { label: 'Nutri-Life BAM', nutrientContent: {}, description: 'A source of beneficial anaerobic (facultative) microbes that can increase organic matter decomposition levels and nutrient cycling, also helping enhance plant resilience.' },
  { label: 'Borax', nutrientContent: { Boron: 14 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'moderate' },
  { label: 'Cobalt Sulfate Heptahydrate', nutrientContent: { Cobalt: 21 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Copper Sulfate', nutrientContent: { Copper: 25 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Dolomite', nutrientContent: { Calcium: 20, Magnesium: 10 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'slow' },
  { label: 'Gran Am', nutrientContent: { Ammonium: 20, Sulphur: 24 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Granulated Boric Acid', nutrientContent: { Boron: 17.5 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'moderate' },
  { label: 'Granulated Copper Sulfate', nutrientContent: { Copper: 25 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Granulated Zinc Mono', nutrientContent: { Zinc: 35 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Guano', nutrientContent: { Calcium: 30, Phosphorus: 13 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'slow' },
  { label: 'Iron Sulfate', nutrientContent: { Iron: 18 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Magnesite', nutrientContent: { Magnesium: 27 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'slow' },
  { label: 'Magnesium Oxide', nutrientContent: { Magnesium: 53 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'slow' },
  { label: 'Magnesium Sulfate', nutrientContent: { Magnesium: 9.9, Sulphur: 13 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Manganese Sulfate', nutrientContent: { Manganese: 31 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Mono Potassium Phosphate (MKP)', nutrientContent: { Potassium: 28, Phosphorus: 22 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Natural Gypsum', nutrientContent: { Calcium: 20, Sulphur: 15 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'moderate' },
  { label: 'NTS Stabilised Boron Granules™', nutrientContent: { Boron: 3.3 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'moderate' },
  { label: 'Sodium Molybdate', nutrientContent: { Molybdenum: 39 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Super Fine Ag Lime', nutrientContent: { Calcium: 40 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'slow' },
  { label: 'Zinc Sulfate Heptahydrate', nutrientContent: { Zinc: 22, Sulphur: 11 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
  { label: 'Zinc Sulfate Monohydrate', nutrientContent: { Zinc: 34, Sulphur: 15 }, phLogic: { min_pH: null, max_pH: null }, releaseType: 'fast' },
 
  // Add more as needed
];

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function formatNutrientBreakdown(nutrientContent) {
  if (!nutrientContent || Object.keys(nutrientContent).length === 0) return '';
  return Object.entries(nutrientContent)
    .map(([nutrient, value]) => `${nutrient}: ${value}%`)
    .join(', ');
}

export const soilDrenchProducts = productList.map(product => ({
  ...product,
  value: slugify(product.label),
  defaultRate: '1',
  defaultUnit: 'L/ha',
  contains: [],
  nutrientPercents: [],
  nutrientBreakdown: formatNutrientBreakdown(product.nutrientContent),
}));

export const foliarSprayProducts = productList.map(product => ({
  ...product,
  value: slugify(product.label),
  defaultRate: '1',
  defaultUnit: 'L/ha',
  contains: [],
  nutrientPercents: [],
  nutrientBreakdown: formatNutrientBreakdown(product.nutrientContent),
}));

export const ammoniumNitrateFerts = [
  {
    name: "Calcium Nitrate",
    n_form: "Nitrate (NO₃⁻)",
    nitrate: 15.5,
    P2O5: 0,
    K2O: 0,
    Ca: 19,
    S: 0,
    Na: 0,
    Cl: 0,
    description: "Supplies fast-acting nitrate nitrogen and calcium. Used in fertigation and hydroponics."
  },
  {
    name: "Potassium Nitrate",
    n_form: "Nitrate (NO₃⁻)",
    nitrate: 13,
    P2O5: 0,
    K2O: 44,
    Ca: 0,
    S: 0,
    Na: 0,
    Cl: 0,
    description: "Provides nitrate and potassium. Ideal for fruiting/flowering crops."
  },
  {
    name: "Sodium Nitrate",
    n_form: "Nitrate (NO₃⁻)",
    nitrate: 16,
    P2O5: 0,
    K2O: 0,
    Ca: 0,
    S: 0,
    Na: 26,
    Cl: 0,
    description: "Known as Chilean nitrate. Fast-acting and approved for some organic systems."
  },
  {
    name: "Ammonium Nitrate",
    n_form: "NO₃⁻ + NH₄⁺",
    nitrate: 17,
    ammonium: 17,
    P2O5: 0,
    K2O: 0,
    Ca: 0,
    S: 0,
    Na: 0,
    Cl: 0,
    description: "Balanced source of nitrate and ammonium N. Restricted in some countries."
  },
  {
    name: "Ammonium Sulfate",
    n_form: "Ammonium (NH₄⁺)",
    ammonium: 21,
    P2O5: 0,
    K2O: 0,
    Ca: 0,
    S: 24,
    Na: 0,
    Cl: 0,
    description: "Provides ammonium N and sulfur. Useful for acidifying soil."
  },
  {
    name: "Anhydrous Ammonia",
    n_form: "Ammonium (via NH₃)",
    ammonium: 82,
    P2O5: 0,
    K2O: 0,
    Ca: 0,
    S: 0,
    Na: 0,
    Cl: 0,
    description: "Highest %N of any fertilizer. Injected into soil."
  },
  {
    name: "Aqua Ammonia",
    n_form: "Ammonium",
    ammonium: 22.5,
    P2O5: 0,
    K2O: 0,
    Ca: 0,
    S: 0,
    Na: 0,
    Cl: 0,
    description: "Liquid ammonia; used in irrigation or injection."
  },
  {
    name: "Ammonium Chloride",
    n_form: "Ammonium",
    ammonium: 26,
    P2O5: 0,
    K2O: 0,
    Ca: 0,
    S: 0,
    Na: 0,
    Cl: 66,
    description: "Boosts ammonium N; also supplies chloride. Used in cereals and rice."
  },
  {
    name: "DAP (Diammonium Phosphate)",
    n_form: "Ammonium",
    ammonium: 18,
    P2O5: 46,
    K2O: 0,
    Ca: 0,
    S: 0,
    Na: 0,
    Cl: 0,
    description: "Supplies both ammonium N and phosphorus. Common starter fertilizer."
  }
]; 